version: "3"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: emmadozengrapes_production_django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
