# Generated by Django 3.0.8 on 2020-07-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default='', max_length=150, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
