# Generated by Django 3.0.8 on 2020-07-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
