# Generated by Django 3.0.8 on 2020-07-21 18:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('timestamp', models.DateField(verbose_name='Date Last Updated')),
                ('body', wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(classname='about-title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('two_images', wagtail.core.blocks.StructBlock([('left_image', wagtail.images.blocks.ImageChooserBlock()), ('right_image', wagtail.images.blocks.ImageChooserBlock())]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
